// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mwdev22/booking/booking"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingStore creates a new instance of MockBookingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingStore {
	mock := &MockBookingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingStore is an autogenerated mock type for the BookingStore type
type MockBookingStore struct {
	mock.Mock
}

type MockBookingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingStore) EXPECT() *MockBookingStore_Expecter {
	return &MockBookingStore_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockBookingStore
func (_mock *MockBookingStore) Cancel(ctx context.Context, bookingID string) error {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingStore_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockBookingStore_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockBookingStore_Expecter) Cancel(ctx interface{}, bookingID interface{}) *MockBookingStore_Cancel_Call {
	return &MockBookingStore_Cancel_Call{Call: _e.mock.On("Cancel", ctx, bookingID)}
}

func (_c *MockBookingStore_Cancel_Call) Run(run func(ctx context.Context, bookingID string)) *MockBookingStore_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingStore_Cancel_Call) Return(err error) *MockBookingStore_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingStore_Cancel_Call) RunAndReturn(run func(ctx context.Context, bookingID string) error) *MockBookingStore_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingStore
func (_mock *MockBookingStore) Create(ctx context.Context, b *booking.Booking) (string, error) {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *booking.Booking) (string, error)); ok {
		return returnFunc(ctx, b)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *booking.Booking) string); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *booking.Booking) error); ok {
		r1 = returnFunc(ctx, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - b *booking.Booking
func (_e *MockBookingStore_Expecter) Create(ctx interface{}, b interface{}) *MockBookingStore_Create_Call {
	return &MockBookingStore_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *MockBookingStore_Create_Call) Run(run func(ctx context.Context, b *booking.Booking)) *MockBookingStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *booking.Booking
		if args[1] != nil {
			arg1 = args[1].(*booking.Booking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingStore_Create_Call) Return(s string, err error) *MockBookingStore_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBookingStore_Create_Call) RunAndReturn(run func(ctx context.Context, b *booking.Booking) (string, error)) *MockBookingStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockBookingStore
func (_mock *MockBookingStore) GetByID(ctx context.Context, id string) (*booking.Booking, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*booking.Booking, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *booking.Booking); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBookingStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookingStore_Expecter) GetByID(ctx interface{}, id interface{}) *MockBookingStore_GetByID_Call {
	return &MockBookingStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBookingStore_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockBookingStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingStore_GetByID_Call) Return(booking1 *booking.Booking, err error) *MockBookingStore_GetByID_Call {
	_c.Call.Return(booking1, err)
	return _c
}

func (_c *MockBookingStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*booking.Booking, error)) *MockBookingStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockBookingStore
func (_mock *MockBookingStore) GetByUserID(ctx context.Context, userID string, filters *booking.ListFilters) ([]*booking.Booking, error) {
	ret := _mock.Called(ctx, userID, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*booking.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *booking.ListFilters) ([]*booking.Booking, error)); ok {
		return returnFunc(ctx, userID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *booking.ListFilters) []*booking.Booking); ok {
		r0 = returnFunc(ctx, userID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *booking.ListFilters) error); ok {
		r1 = returnFunc(ctx, userID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingStore_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockBookingStore_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - filters *booking.ListFilters
func (_e *MockBookingStore_Expecter) GetByUserID(ctx interface{}, userID interface{}, filters interface{}) *MockBookingStore_GetByUserID_Call {
	return &MockBookingStore_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID, filters)}
}

func (_c *MockBookingStore_GetByUserID_Call) Run(run func(ctx context.Context, userID string, filters *booking.ListFilters)) *MockBookingStore_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *booking.ListFilters
		if args[2] != nil {
			arg2 = args[2].(*booking.ListFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingStore_GetByUserID_Call) Return(bookings []*booking.Booking, err error) *MockBookingStore_GetByUserID_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingStore_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string, filters *booking.ListFilters) ([]*booking.Booking, error)) *MockBookingStore_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBookingStore
func (_mock *MockBookingStore) List(ctx context.Context, filters *booking.ListFilters) ([]*booking.Booking, int, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*booking.Booking
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *booking.ListFilters) ([]*booking.Booking, int, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *booking.ListFilters) []*booking.Booking); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*booking.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *booking.ListFilters) int); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *booking.ListFilters) error); ok {
		r2 = returnFunc(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBookingStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBookingStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *booking.ListFilters
func (_e *MockBookingStore_Expecter) List(ctx interface{}, filters interface{}) *MockBookingStore_List_Call {
	return &MockBookingStore_List_Call{Call: _e.mock.On("List", ctx, filters)}
}

func (_c *MockBookingStore_List_Call) Run(run func(ctx context.Context, filters *booking.ListFilters)) *MockBookingStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *booking.ListFilters
		if args[1] != nil {
			arg1 = args[1].(*booking.ListFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingStore_List_Call) Return(bookings []*booking.Booking, n int, err error) *MockBookingStore_List_Call {
	_c.Call.Return(bookings, n, err)
	return _c
}

func (_c *MockBookingStore_List_Call) RunAndReturn(run func(ctx context.Context, filters *booking.ListFilters) ([]*booking.Booking, int, error)) *MockBookingStore_List_Call {
	_c.Call.Return(run)
	return _c
}
