// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mwdev22/booking/booking"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlaceStore creates a new instance of MockPlaceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlaceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlaceStore {
	mock := &MockPlaceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlaceStore is an autogenerated mock type for the PlaceStore type
type MockPlaceStore struct {
	mock.Mock
}

type MockPlaceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlaceStore) EXPECT() *MockPlaceStore_Expecter {
	return &MockPlaceStore_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockPlaceStore
func (_mock *MockPlaceStore) GetByID(ctx context.Context, id string) (*booking.Place, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *booking.Place
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*booking.Place, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *booking.Place); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*booking.Place)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaceStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPlaceStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPlaceStore_Expecter) GetByID(ctx interface{}, id interface{}) *MockPlaceStore_GetByID_Call {
	return &MockPlaceStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPlaceStore_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockPlaceStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaceStore_GetByID_Call) Return(place *booking.Place, err error) *MockPlaceStore_GetByID_Call {
	_c.Call.Return(place, err)
	return _c
}

func (_c *MockPlaceStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*booking.Place, error)) *MockPlaceStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockPlaceStore
func (_mock *MockPlaceStore) Search(ctx context.Context, query string, category string, limit int) ([]*booking.Place, error) {
	ret := _mock.Called(ctx, query, category, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*booking.Place
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) ([]*booking.Place, error)); ok {
		return returnFunc(ctx, query, category, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) []*booking.Place); ok {
		r0 = returnFunc(ctx, query, category, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*booking.Place)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, query, category, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaceStore_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockPlaceStore_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - category string
//   - limit int
func (_e *MockPlaceStore_Expecter) Search(ctx interface{}, query interface{}, category interface{}, limit interface{}) *MockPlaceStore_Search_Call {
	return &MockPlaceStore_Search_Call{Call: _e.mock.On("Search", ctx, query, category, limit)}
}

func (_c *MockPlaceStore_Search_Call) Run(run func(ctx context.Context, query string, category string, limit int)) *MockPlaceStore_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPlaceStore_Search_Call) Return(places []*booking.Place, err error) *MockPlaceStore_Search_Call {
	_c.Call.Return(places, err)
	return _c
}

func (_c *MockPlaceStore_Search_Call) RunAndReturn(run func(ctx context.Context, query string, category string, limit int) ([]*booking.Place, error)) *MockPlaceStore_Search_Call {
	_c.Call.Return(run)
	return _c
}
